### ISSUE TITLE
Add `func` argument to `compute_MVBS`

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echopype#1268]
The addition of the `func` argument will enable users to specify the aggregation function used by the underlying `flox.xarray.xarray_reduce`. This `func` parameter determines how the aggregation is performed on the Sv data array. By default, this function is set to `nanmean`, but users can opt to use other aggregate functions like `mean` in the case where they want to NaN any MVBS bin that 'contains' NaN values in the original Sv grid.

One can find all available options for func listed here: https://flox.readthedocs.io/en/latest/generated/flox.xarray.xarray_reduce.html.

**Comment by leewujung** [comment]
We close this now with #1269 merged. Also that since compute_MVBS is supposed to be a mean or nanmean function, we don't need to include the flexibility of allowing different `func`. But the intermediate function under the hood does allow that and we'll likely use them for other processing functions later.
