### ISSUE TITLE
Eager computation in `compute_MVBS` setting of attributes

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echopype#1378]
There exists eager computation in `compute_MVBS` when setting the `actual_range` attributes:

```
    ds_MVBS["Sv"] = ds_MVBS["Sv"].assign_attrs(
        {
            "cell_methods": (
                f"ping_time: mean (interval: {ping_time_bin_resvalue} {ping_time_bin_resunit_label} "  # noqa
                "comment: ping_time is the interval start) "
                f"{range_var}: mean (interval: {range_bin} meter "
                f"comment: {range_var} is the interval start)"
            ),
            "binning_mode": "physical units",
            "range_meter_interval": str(range_bin) + "m",
            "ping_time_interval": ping_time_bin,
            "actual_range": [
                round(float(ds_MVBS["Sv"].min().values), 2),
                round(float(ds_MVBS["Sv"].max().values), 2),
            ],
        }
    )
```
https://github.com/OSOceanAcoustics/echopype/blob/be2b86cc668b59b0b856789de29614bcc25000bd/echopype/commongrid/api.py#L164C1-L183C6

The calling of `.values` evaluates the `.min()` and `.max()`. The `actual_range` attribute should be removed so that the function can be kept entirely lazy.

**Comment by leewujung** [comment]
I wonder if this is something that we can do as a side function at the end of the `compute_MVBS` code. So instead of having this and preventing the computation to be lazy, we do all ops needed to get the MVBS datasets first, and then call a function to lazily find the min/max and assign these values to the attributes before existing the `computer_MVBS` function.
