### ISSUE TITLE
Handle parameter changes across multiple files when combining for EK60/EK80

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#180]
When combining, parameters like sound speed and seawater absorption are taken only from the first raw file, but these values can change between files. There does not seem to be a practical way of saving, for example, multiple sound speed values as there is no dimension along which to concatenate these values. So a warning should be given and the first value will be used in the combination.

- [ ] Check for a changing value
- [ ] Give a warning that a value changed
- [ ] Print the values

Then proceed with combination.

**Comment by leewujung** [comment]
This issue is outdated since the code has had substantial changes and the encoding of env parameters are different for different instruments. I'll close this now and have duplicated my comments below to the new issue #364 that focuses on combining multiple EchoData objects.

Notes:
- For EK60: these parameters are encoded with each ping (each sample datagram)
- For EK80: these parameters are encoded with a single ping_time before all sample datagrams
- For AZFP: temperature and pressure of the instrument is recorded with each ping, but not salinity, which has to be supplied by the user during calibration.
