### ISSUE TITLE
Improve printouts when converting file

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#241]
In the dev branch `class-redesign` echopype prints out the following:
```
17:40:42  converting FILENAME.zarr
17:40:43  parsing file FILENAME.raw, time of first ping: 2017-Nov-13 22:55:43
```
The messages can be improved to show the stage of conversion. Something like: 
```
HH:MM:SS  start converting FILENAME.raw
HH:MM:SS  parsing file FILENAME.raw, time of first ping: 2017-11-13T22:55:43
HH:MM:SS  saving file FILENAME.zarr to LOCATION
# if parsing fails
HH:MM:SS  file parsing fails due to the following error:
[ERROR MESSAGES]
# if saving fails
HH:MM:SS  file saving fails due to the following error:
[ERROR MESSAGES]
```

**Comment by ngkavin** [comment]
After discussing with @leewujung , we have decided that the current printouts are adequate for providing the user with clear and concise information on where they are in the conversion process.

The current printouts look like this:
```
11:49:21  parsing file FILENAME.01A with XML_FILENAME.XML, time of first ping: 2017-Aug-21 17:05:37
11:49:21  saving ABSOLUTE_FILE_DIR/FILENAME.nc
```

The first line is printed during `open_raw` and the second is printed during `.to_netcdf` or `.to_zarr`. The starting conversion and the error printouts are no longer required because conversion and saving is done in two separate steps whereas previously, calling `to_netcdf` would both parse and save the file which could cause some confusion on where errors occur.
