### ISSUE TITLE
Are we fully deprecating use of Git LFS?

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#271]
The documentation retains the [text about the use of Git LFS](https://doc-test-echopype.readthedocs.io/en/latest/contributing.html#test-files). But I think we've effectively stopped using LFS, right? If so, should I remove that text from the docs altogether?

ref: #268

**Comment by leewujung** [comment]
Yes, I agree we should remove LFS text from the docs!

**Comment by leewujung** [comment]
This issue can be closed one `class-redesign` is merged to `master`.

**Comment by leewujung** [comment]
Closing this with #298.

**Comment by leewujung** [comment]
We will need to remove all test files from the repo, and potentially "rewrite" the history to fully deprecate use of Git LFS (hopefully not needed!) to actually close this. But this does not impact releasing v0.5.0.

**Comment by lsetiawan** [comment]
This may help us: https://github.com/git-lfs/git-lfs/issues/3026

**Comment by leewujung** [comment]
Great, thanks for pointing to this @lsetiawan . Let's make sure to experiment with a duplicated dummy first 😅.

**Comment by lsetiawan** [comment]
With #369 merged. When I do `git lfs ls-files` nothing shows up, I assume that means it's not stored in lfs.

**Comment by leewujung** [comment]
When I do `git lfs ls-files` I still get a whole list of files, but we can probably live with that for now, as long as folks don't have to do pull files from git lfs when they try to contribute.

**Comment by leewujung** [comment]
An additional note: @lsetiawan since you're on this, could you remove all the LFS related stuff under `.gitattributes`? Thanks.

**Comment by lsetiawan** [comment]
> When I do git lfs ls-files I still get a whole list of files,

Are you on the branch associated with #369?

**Comment by lsetiawan** [comment]
>could you remove all the LFS related stuff under .gitattributes? Thanks.

That should be all deleted now on dev branch.

**Comment by leewujung** [comment]
Great, now under dev when i do `git lfs ls-files` I don't see anything.

**Comment by leewujung** [comment]
Reopening this issue because there are still some hidden problems related to Git LFS, which show up when maintainers try to push to the PR forks (@lsetiawan and I both ran into this). The workaround has been to skip pre-hook as discussed [here](https://github.com/git-lfs/git-lfs/issues/2291) and we should probably fix the source of the problem. From other people's reporting it seems that this could cause problems to contributors also depending on what commits they pull.

Completely removing LFS from the repo appears to be a common need and a casual search turned up [this](https://bryanbrattlof.com/removing-git-lfs-from-a-project/). Not sure if there is a better solution. I did the "rewrite history" part when adding LFS to the repo. It is pretty terrible because people need to delete and refork, otherwise the history don't match.

@lsetiawan : thoughts?

**Comment by leewujung** [comment]
Let's investigate this as part of the test overhaul in 0.6.4, but not delaying this further so that we can once and for all be happy that we don't have LFS constraints anymore.

**Comment by leewujung** [comment]
I'll close this now but if problems surface later we'll reopen it.
